window.__BIBLIOS_SEARCH_INDEX__ = [
  {"component":"interlis-lab-demo","version":"main","displayVersion":"v0.0.1","kind":"chapter","title":"1. Lernpfad","pageTitle":"INTERLIS Lab Demo","sectionPath":"1. Lernpfad","sectionLevel":1,"route":"/interlis-lab-demo/main/#_lernpfad","content":"1. Lernpfad Eine erste CLASS mit einem Attribut ergänzen Obligatorische und optionale Attribute unterscheiden Eigene DOMAIN und eine kleine Enumeration einführen Compilerfehler bei Blöcken systematisch beheben Eine erste ASSOCIATION zwischen zwei Klassen formulieren"},
  {"component":"interlis-lab-demo","version":"main","displayVersion":"v0.0.1","kind":"chapter","title":"2. Übungen","pageTitle":"INTERLIS Lab Demo","sectionPath":"2. Übungen","sectionLevel":1,"route":"/interlis-lab-demo/main/#_übungen","content":"2. Übungen Übung 1: Deine erste Klasse Übung 2: Pflichtfelder und Bereich Übung 3: Domain und Enumeration Übung 4: Debugging von END-Blöcken Übung 5: Erste Association"},
  {"component":"interlis-lab-demo","version":"main","displayVersion":"v0.0.1","kind":"page","title":"Übung 1: Deine erste Klasse","pageTitle":"Übung 1: Deine erste Klasse","sectionPath":"Übung 1: Deine erste Klasse","sectionLevel":0,"route":"/interlis-lab-demo/main/01-erste-klasse/","content":"Der Einstieg beginnt bewusst klein: eine einzelne Klasse mit genau einem Attribut. Übung 1: Deine erste Klasse"},
  {"component":"interlis-lab-demo","version":"main","displayVersion":"v0.0.1","kind":"page","title":"Übung 2: Pflichtfelder und Bereich","pageTitle":"Übung 2: Pflichtfelder und Bereich","sectionPath":"Übung 2: Pflichtfelder und Bereich","sectionLevel":0,"route":"/interlis-lab-demo/main/02-pflichtfelder-und-bereich/","content":"Jetzt kommt ein zweiter Schritt dazu: ein obligatorisches Textfeld und ein Zahlenbereich. Übung 2: Pflichtfelder und Bereich"},
  {"component":"interlis-lab-demo","version":"main","displayVersion":"v0.0.1","kind":"page","title":"Übung 3: Domain und Enumeration","pageTitle":"Übung 3: Domain und Enumeration","sectionPath":"Übung 3: Domain und Enumeration","sectionLevel":0,"route":"/interlis-lab-demo/main/03-domain-und-enum/","content":"Ab hier kapselst du einen Typ in einer DOMAIN und ergänzt zusätzlich eine kleine Enumeration. Übung 3: Domain und Enumeration"},
  {"component":"interlis-lab-demo","version":"main","displayVersion":"v0.0.1","kind":"page","title":"Übung 4: Debugging von END-Blöcken","pageTitle":"Übung 4: Debugging von END-Blöcken","sectionPath":"Übung 4: Debugging von END-Blöcken","sectionLevel":0,"route":"/interlis-lab-demo/main/04-debugging-end-bloecke/","content":"In dieser Aufgabe gehst du stärker über Compilerfehler: ein fehlendes Semikolon und vertauschte END-Blöcke müssen zusammen korrigiert werden. Übung 4: Debugging von END-Blöcken"},
  {"component":"interlis-lab-demo","version":"main","displayVersion":"v0.0.1","kind":"page","title":"Übung 5: Erste Association","pageTitle":"Übung 5: Erste Association","sectionPath":"Übung 5: Erste Association","sectionLevel":0,"route":"/interlis-lab-demo/main/05-erste-association/","content":"Zum Schluss verbindest du zwei Klassen mit einer einfachen ASSOCIATION. Übung 5: Erste Association"}
];
